// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKzCp19bTZjN96zeY-ta9fv8SanjmRiSU',
    appId: '1:217319616283:web:405cab887612272f0cedbe',
    messagingSenderId: '217319616283',
    projectId: 'bolshek-push',
    authDomain: 'bolshek-push.firebaseapp.com',
    storageBucket: 'bolshek-push.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZvNdMYSJ_PzBvsOXYBB9LRbzhVrmb8v4',
    appId: '1:217319616283:android:81bd7abb26a907b20cedbe',
    messagingSenderId: '217319616283',
    projectId: 'bolshek-push',
    storageBucket: 'bolshek-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVmF0OaThChLGqu4nPBBzMJvWemzBlgIo',
    appId: '1:217319616283:ios:dd60b9a699bbe4840cedbe',
    messagingSenderId: '217319616283',
    projectId: 'bolshek-push',
    storageBucket: 'bolshek-push.firebasestorage.app',
    iosBundleId: 'com.bolsheksatu.net',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVmF0OaThChLGqu4nPBBzMJvWemzBlgIo',
    appId: '1:217319616283:ios:d8dcba2f3593bc800cedbe',
    messagingSenderId: '217319616283',
    projectId: 'bolshek-push',
    storageBucket: 'bolshek-push.firebasestorage.app',
    iosBundleId: 'com.example.bolshekPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKzCp19bTZjN96zeY-ta9fv8SanjmRiSU',
    appId: '1:217319616283:web:61becca1d202745f0cedbe',
    messagingSenderId: '217319616283',
    projectId: 'bolshek-push',
    authDomain: 'bolshek-push.firebaseapp.com',
    storageBucket: 'bolshek-push.firebasestorage.app',
  );
}
