name: bolshek_pro
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_svg: ^2.0.14
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.1
  path: ^1.9.0
  uuid: ^4.5.1
  pretty_http_logger: ^1.0.4
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/icon_bolshek_2.png"
  image_path_ios: "assets/icons/icon_bolshek_2.png"
  remove_alpha_ios: true



flutter:
  assets:
    - assets/svg/
 


  uses-material-design: true

