name: bolshek_pro
description: "A new Flutter project."

version: 1.0.9+20

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  # path_provider: ^2.0.14
  dio: ^5.7.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_svg: ^2.0.14
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.1
  path: ^1.9.0
  uuid: ^4.5.1
  mask_text_input_formatter: ^2.9.0
  translit: ^2.0.2
  pin_code_fields: ^8.0.1
  pretty_http_logger: ^1.0.4
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  collection: ^1.18.0
  intl: ^0.19.0
  extended_tabs: ^4.2.0
  photo_view: ^0.15.0
  yandex_mapkit: ^4.1.0
  location: ^7.0.1
  url_launcher: ^6.3.1
  firebase_messaging: ^15.1.6
  firebase_core: ^3.10.0
  flutter_local_notifications: ^18.0.1
  # image: ^4.5.2
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_bolshek_2.png"
  adaptive_icon_background: "#555555"
  adaptive_icon_foreground: "assets/icons/icon_bolshek_2.png"
  image_path_ios: "assets/icons/icon_bolshek_2.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icons/
    - assets/icons/location.png
    - assets/fonts/

  fonts:
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
