name: bolshek_pro
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_svg: ^2.0.14
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/icon_bolshek.png"
  image_path_ios: "assets/icons/icon_bolshek.png"



flutter:
  assets:
    - assets/svg/
 


  uses-material-design: true

