abstract class Constants {
  static const logoText = "Bolshek Satu";
  static const baseUrl = "https://api-stage.bolshek.com";
  // static const baseUrl = "https://api.bolshek.kz";
  static const addCart = "Добавить в корзину";
  static const changeProduct = 'Редактировать';
  static const fromSale = 'Снять с продажи';
  static const activeStatus = 'status=active';
  static const inactiveStatus = 'status=inactive';
  static const awaitingStatus = 'statuses=created&statuses=updated';
  static const addNewGood = 'Добавить новый товар';
  static const nameHint = "Имя";
  static const phone = "Телефон";
  static const shop = "Магазин";
  static const catalog = "Каталог";
  static const fav = "Избранное";
  static const bag = "Корзина";
  static const order = "Мои заказы";
  static const searchHint = "Поиск запчастей";
  static const category = "Категория";
  static const wacthed = "Популярные товары";
  static const watchAllProduct = "Смотреть все товары";
  static const howItWorks = "Как это работает?";
  static const takePicCar = "Сфотографируйте номер авто";
  static const writeCarNumber = "Ввести Номер авто";
  static const orWriteCar = "Или выбрать марка и модель авто";
  static const correctAnswer = "Выберите правильный номер";
  static const inputCarAuto = "Введите номер тех паспорта";
  static const select = "Выбрать";
  static const continueW = "Продолжить";
  static const marka = "Марка";
  static const selectedMarka = "Выбранная марка";
  static const allMarka = "Все марки";
  static const scanNumber = "Сканировать номер авто";
  static const scanTechPassport = "Сканировать техпасторт";
  static const addCar = "Добавить авто";
  static const noCarVin = "Авто с этим VIN-кодом не найдено";
  static const fixVin = "Исправить VIN-код";
  static const backMain = "Вернуться на главную";
  static const approve = "Подтверждение";
  static const yourCar = "Ваш автомобиль";
  static const vinFromPassport = "VIN-код из техпаспорта:";
  static const pleaseInputPhone = "Пожалуйста, заполните телефон";
  static const getSmsCode = "Получить код в СМС";
  static const logout = "Выйти";
  static const regetSmsCode = "Получить код в СМС еще раз";
  static const myData = "Мои данные";
  static const myCard = "Мои карты";
  static const myCar = "Мои машины";
  static const notification = "Уведомление";
  static const quit = "Выйти";
  static const clear = "Очистить";
  static const goShop = "Перейти к оформлению";
  static const emptyBag = "Ваша корзина пока пуста";
  static const emptyFav = "Здесь пока ничего нет";
  static const needAuth = "Нужно зарегистрироваться";
  static const emptyOrder = "Здесь пока ничего нет";
  static const orderEmpty = "У вас нет заказов";
  static const accept = "Подтвердить";
  static const status = "Статус";
  static const emptyBagLower = "Здесь будут лежать товары для покупки";
  static const emptyFavLower =
      "Добавляйте любимые товары в избранное, чтобы не искать их снова";

  static const welcome = "Добро пожаловать в Bolshek";
  static const welcome1 = "Введите номер телефона";
  static const welcomeInputText =
      "Мы используем ваш номер телефона для уведомлений о заказе";
  static const welcomePinCodeText = "Подтвердите указанный номер телефона";
  static const pinCodeText = "Введите код, отправленный на номер телефона";

  static const transmissia = "Трансмиссия";
  static const systemaVipuska = "Система выпуска";
  static const engineComponents = "Двигатель и компоненты";
  static const hodovaya = "Ходовая часть";
  static const systemaOchlazdenia = "Система охлождения";
  static const masloFilter = "Масло и фильтры";
  static const tormoz = "Тормозная система";
  static const shina = "Шины и диски";
  static const avtoLampi = "Автолампы и Оптика";
  static const electro = "Электро оборудование";
  static const himiya = "Акксессуры и Автохимия";
  static const kuzovDetali = "Кузовные детали";
  static const maybeInteresting = "Вас могут заинтересовать";
  static const statusGiven = "Выдан";
  static const repeatOrder = "Повторить заказ";
  static const detailOrder = "Детали заказа";
  static const vozvratOrder = "Оформить возврат";
  static const dostavka = "Доставка";
  static const itogo = "Итого";
  static const addBag = "Добавлено в корзину";
  static const goBag = "Перейти в корзину";

  static const relevantSort = "По умолчанию";
  static const nameSort = "По наименованию";
  static const priceUpSort = "Цена по возрастанию";
  static const priceDownSort = "Цена по убыванию";
  static const dateSort = "По дате";
  static const filter = "Фильтры";
  static const dropFilter = "Сбросить";
  static const noPermission = "Нету доступа";
  static const openSettings = "Открыть настройки";
  static const cancel = "Отмена";

  static const prize = "Цена";
  static const brand = "Бренды";
  static const accept1 = "Подтвердить";
}
